DOMAIN_FAMILIES: dict[str, dict] = {
    # Tier 1: Pure HTTP redirect — handled by redirect.py
    "bit.ly": {"type": "shortener", "tier": 1},
    "tinyurl.com": {"type": "shortener", "tier": 1},
    "t.co": {"type": "shortener", "tier": 1},
    "is.gd": {"type": "shortener", "tier": 1},
    "v.gd": {"type": "shortener", "tier": 1},
    "ow.ly": {"type": "shortener", "tier": 1},
    "buff.ly": {"type": "shortener", "tier": 1},
    "cutt.ly": {"type": "shortener", "tier": 1},
    "rb.gy": {"type": "shortener", "tier": 1},
    "tiny.one": {"type": "shortener", "tier": 1},
    "shorturl.at": {"type": "shortener", "tier": 1},
    "shorturl.ac": {"type": "shortener", "tier": 1},
    "rebrand.ly": {"type": "shortener", "tier": 1},
    "t.ly": {"type": "shortener", "tier": 1},
    "tiny.cc": {"type": "shortener", "tier": 1},
    "cl.gy": {"type": "shortener", "tier": 1},
    "shorter.me": {"type": "shortener", "tier": 1},
    "lnkd.in": {"type": "shortener", "tier": 1},
    "short.gy": {"type": "shortener", "tier": 1},
    "shorl.com": {"type": "shortener", "tier": 1},
    "bl.ink": {"type": "shortener", "tier": 1},
    "short.io": {"type": "shortener", "tier": 1},
    "dub.co": {"type": "shortener", "tier": 1},
    "short.cm": {"type": "shortener", "tier": 1},

    # Tier 2: Ad-wall with HTML/meta-refresh
    "adf.ly": {"type": "adwall", "tier": 2},
    "adfoc.us": {"type": "adwall", "tier": 2},
    "sh.st": {"type": "adwall", "tier": 2},
    "shorte.st": {"type": "adwall", "tier": 2},
    "bc.vc": {"type": "adwall", "tier": 2},
    "za.gl": {"type": "adwall", "tier": 2},
    "fc.lc": {"type": "adwall", "tier": 2},
    "ay.live": {"type": "adwall", "tier": 2},
    "gestyy.com": {"type": "adwall", "tier": 2},
    "shortconnect.com": {"type": "adwall", "tier": 2},
    "thin.fi": {"type": "adwall", "tier": 2},

    # Tier 3: JS-gated ad networks
    "linkvertise.com": {"type": "adwall_js", "tier": 3},
    "ouo.io": {"type": "adwall_js", "tier": 3},
    "ouo.press": {"type": "adwall_js", "tier": 3},
    "exe.io": {"type": "adwall_js", "tier": 3},
    "gplinks.co": {"type": "adwall_js", "tier": 3},
    "try2link.com": {"type": "adwall_js", "tier": 3},
    "ez4short.com": {"type": "adwall_js", "tier": 3},
    "rocklinks.net": {"type": "adwall_js", "tier": 3},
    "droplink.co": {"type": "adwall_js", "tier": 3},
    "tnlink.in": {"type": "adwall_js", "tier": 3},
    "shrinkme.io": {"type": "adwall_js", "tier": 3},
    "earn4link.in": {"type": "adwall_js", "tier": 3},
    "shareus.in": {"type": "adwall_js", "tier": 3},
    "shortingly.me": {"type": "adwall_js", "tier": 3},
    "xpshort.com": {"type": "adwall_js", "tier": 3},
    "adrinolinks.in": {"type": "adwall_js", "tier": 3},
    "mdiskshortner.link": {"type": "adwall_js", "tier": 3},
    "pdiskshortener.com": {"type": "adwall_js", "tier": 3},
    "linkpays.in": {"type": "adwall_js", "tier": 3},

    # Tier 4: Social unlock
    "sub2unlock.com": {"type": "social", "tier": 4},
    "sub2unlock.net": {"type": "social", "tier": 4},
    "sub4unlock.com": {"type": "social", "tier": 4},
    "rekonise.com": {"type": "social", "tier": 4},
    "mboost.me": {"type": "social", "tier": 4},
    "social-unlock.com": {"type": "social", "tier": 4},
    "ytsubme.com": {"type": "social", "tier": 4},
    "boost.ink": {"type": "social", "tier": 4},
    "work.ink": {"type": "social", "tier": 4},
    "unlocknow.net": {"type": "social", "tier": 4},
    "letsboost.net": {"type": "social", "tier": 4},

    # Tier 5: Drive sharers
    "gdtot.com": {"type": "drive", "tier": 5},
    "sharer.pw": {"type": "drive", "tier": 5},
    "hubdrive.net": {"type": "drive", "tier": 5},
    "katdrive.net": {"type": "drive", "tier": 5},
    "drivefire.net": {"type": "drive", "tier": 5},
    "kolop.net": {"type": "drive", "tier": 5},
    "appdrive.in": {"type": "drive", "tier": 5},
}
