"""Domain family registry — maps shortener domains to bypass strategy tiers.

Tiers:
  1 = Pure HTTP redirect (301/302 follow)
  2 = Ad-wall with HTML/meta-refresh / Form POST
  3 = JS-gated ad networks (requires SmartResolver or Playwright)
  4 = Social unlock (YouTube subscribe, etc.)
  5 = Drive sharers (GDTot, HubDrive, etc.)
"""

DOMAIN_FAMILIES: dict[str, dict] = {
    # ═══════════════════════════════════════════════════════════════
    # Tier 1: Pure HTTP redirect — handled by redirect.py
    # ═══════════════════════════════════════════════════════════════
    "bit.ly": {"type": "shortener", "tier": 1},
    "tinyurl.com": {"type": "shortener", "tier": 1},
    "t.co": {"type": "shortener", "tier": 1},
    "is.gd": {"type": "shortener", "tier": 1},
    "v.gd": {"type": "shortener", "tier": 1},
    "ow.ly": {"type": "shortener", "tier": 1},
    "buff.ly": {"type": "shortener", "tier": 1},
    "cutt.ly": {"type": "shortener", "tier": 1},
    "rb.gy": {"type": "shortener", "tier": 1},
    "tiny.one": {"type": "shortener", "tier": 1},
    "shorturl.at": {"type": "shortener", "tier": 1},
    "shorturl.ac": {"type": "shortener", "tier": 1},
    "rebrand.ly": {"type": "shortener", "tier": 1},
    "t.ly": {"type": "shortener", "tier": 1},
    "tiny.cc": {"type": "shortener", "tier": 1},
    "cl.gy": {"type": "shortener", "tier": 1},
    "shorter.me": {"type": "shortener", "tier": 1},
    "lnkd.in": {"type": "shortener", "tier": 1},
    "short.gy": {"type": "shortener", "tier": 1},
    "shorl.com": {"type": "shortener", "tier": 1},
    "bl.ink": {"type": "shortener", "tier": 1},
    "short.io": {"type": "shortener", "tier": 1},
    "dub.co": {"type": "shortener", "tier": 1},
    "short.cm": {"type": "shortener", "tier": 1},
    "goo.gl": {"type": "shortener", "tier": 1},
    "bit.do": {"type": "shortener", "tier": 1},
    "clck.ru": {"type": "shortener", "tier": 1},
    "s.id": {"type": "shortener", "tier": 1},
    "p.pw": {"type": "shortener", "tier": 1},
    "shorturl.com": {"type": "shortener", "tier": 1},
    "tinyurl.so": {"type": "shortener", "tier": 1},
    "tinyurl.is": {"type": "shortener", "tier": 1},
    "soo.gd": {"type": "shortener", "tier": 1},
    "qr.ae": {"type": "shortener", "tier": 1},
    "wp.me": {"type": "shortener", "tier": 1},
    "buff.ly": {"type": "shortener", "tier": 1},
    "eepurl.com": {"type": "shortener", "tier": 1},
    "ift.tt": {"type": "shortener", "tier": 1},
    "j.mp": {"type": "shortener", "tier": 1},
    "on.fb.me": {"type": "shortener", "tier": 1},
    "migre.me": {"type": "shortener", "tier": 1},
    "shortlinks.com": {"type": "shortener", "tier": 1},
    "x.co": {"type": "shortener", "tier": 1},
    "zpr.io": {"type": "shortener", "tier": 1},

    # ═══════════════════════════════════════════════════════════════
    # Tier 2: Ad-wall with HTML/meta-refresh / Form POST
    # ═══════════════════════════════════════════════════════════════
    "adf.ly": {"type": "adwall", "tier": 2},
    "adfoc.us": {"type": "adwall", "tier": 2},
    "sh.st": {"type": "adwall", "tier": 2},
    "shorte.st": {"type": "adwall", "tier": 2},
    "bc.vc": {"type": "adwall", "tier": 2},
    "za.gl": {"type": "adwall", "tier": 2},
    "fc.lc": {"type": "adwall", "tier": 2},
    "ay.live": {"type": "adwall", "tier": 2},
    "gestyy.com": {"type": "adwall", "tier": 2},
    "shortconnect.com": {"type": "adwall", "tier": 2},
    "thin.fi": {"type": "adwall", "tier": 2},
    "linkbucks.com": {"type": "adwall", "tier": 2},
    "ceesty.com": {"type": "adwall", "tier": 2},
    "corneey.com": {"type": "adwall", "tier": 2},
    "festyy.com": {"type": "adwall", "tier": 2},
    "destyy.com": {"type": "adwall", "tier": 2},
    "clk.ink": {"type": "adwall", "tier": 2},
    "clk.sh": {"type": "adwall", "tier": 2},
    "clk.kim": {"type": "adwall", "tier": 2},
    "clik.pw": {"type": "adwall", "tier": 2},
    "clkmein.com": {"type": "adwall", "tier": 2},
    "cllkme.com": {"type": "adwall", "tier": 2},
    "cash4url.com": {"type": "adwall", "tier": 2},
    "cash4links.co": {"type": "adwall", "tier": 2},
    "shrtfly.com": {"type": "adwall", "tier": 2},
    "shrtn.link": {"type": "adwall", "tier": 2},
    "link1s.com": {"type": "adwall", "tier": 2},
    "link5s.com": {"type": "adwall", "tier": 2},
    "link4ad.net": {"type": "adwall", "tier": 2},
    "linksly.co": {"type": "adwall", "tier": 2},
    "linkshortify.com": {"type": "adwall", "tier": 2},
    "linkshrink.ca": {"type": "adwall", "tier": 2},
    "link-to.net": {"type": "adwall", "tier": 2},
    "link-target.net": {"type": "adwall", "tier": 2},
    "link-hub.net": {"type": "adwall", "tier": 2},
    "lnk.news": {"type": "adwall", "tier": 2},
    "lnk2.cc": {"type": "adwall", "tier": 2},
    "viid.me": {"type": "adwall", "tier": 2},
    "viid.su": {"type": "adwall", "tier": 2},
    "wicr.me": {"type": "adwall", "tier": 2},
    "wi.cr": {"type": "adwall", "tier": 2},
    "fc-lc.com": {"type": "adwall", "tier": 2},
    "fc-lc.xyz": {"type": "adwall", "tier": 2},
    "shorte.top": {"type": "adwall", "tier": 2},
    "shortit.ca": {"type": "adwall", "tier": 2},
    "shortmony.com": {"type": "adwall", "tier": 2},
    "shortpay.net": {"type": "adwall", "tier": 2},
    "shortzon.com": {"type": "adwall", "tier": 2},
    "shrt.co": {"type": "adwall", "tier": 2},
    "t2m.io": {"type": "adwall", "tier": 2},
    "tny.so": {"type": "adwall", "tier": 2},
    "hyperurl.co": {"type": "adwall", "tier": 2},

    # ═══════════════════════════════════════════════════════════════
    # Tier 3: JS-gated ad networks
    # ═══════════════════════════════════════════════════════════════
    "linkvertise.com": {"type": "adwall_js", "tier": 3},
    "linkvertise.net": {"type": "adwall_js", "tier": 3},
    "ouo.io": {"type": "adwall_js", "tier": 3},
    "ouo.press": {"type": "adwall_js", "tier": 3},
    "ouo.info": {"type": "adwall_js", "tier": 3},
    "exe.io": {"type": "adwall_js", "tier": 3},
    "exe.app": {"type": "adwall_js", "tier": 3},
    "exee.app": {"type": "adwall_js", "tier": 3},
    "exee.io": {"type": "adwall_js", "tier": 3},
    "exego.app": {"type": "adwall_js", "tier": 3},
    "exeo.app": {"type": "adwall_js", "tier": 3},
    "exep.app": {"type": "adwall_js", "tier": 3},
    "exey.io": {"type": "adwall_js", "tier": 3},
    "exeylink.com": {"type": "adwall_js", "tier": 3},
    "gplinks.co": {"type": "adwall_js", "tier": 3},
    "gplinks.in": {"type": "adwall_js", "tier": 3},
    "try2link.com": {"type": "adwall_js", "tier": 3},
    "try2links.com": {"type": "adwall_js", "tier": 3},
    "ez4short.com": {"type": "adwall_js", "tier": 3},
    "ez4links.com": {"type": "adwall_js", "tier": 3},
    "ez4mods.com": {"type": "adwall_js", "tier": 3},
    "rocklinks.net": {"type": "adwall_js", "tier": 3},
    "rocklinks.in": {"type": "adwall_js", "tier": 3},
    "droplink.co": {"type": "adwall_js", "tier": 3},
    "droplinks.co": {"type": "adwall_js", "tier": 3},
    "tnlink.in": {"type": "adwall_js", "tier": 3},
    "shrinkme.io": {"type": "adwall_js", "tier": 3},
    "shrinkme.in": {"type": "adwall_js", "tier": 3},
    "shrinkme.cc": {"type": "adwall_js", "tier": 3},
    "shrinkme.click": {"type": "adwall_js", "tier": 3},
    "shrinkme.link": {"type": "adwall_js", "tier": 3},
    "shrinkme.site": {"type": "adwall_js", "tier": 3},
    "shrinkme.vip": {"type": "adwall_js", "tier": 3},
    "earn4link.in": {"type": "adwall_js", "tier": 3},
    "shareus.in": {"type": "adwall_js", "tier": 3},
    "shareus.io": {"type": "adwall_js", "tier": 3},
    "shortingly.me": {"type": "adwall_js", "tier": 3},
    "shortingly.in": {"type": "adwall_js", "tier": 3},
    "xpshort.com": {"type": "adwall_js", "tier": 3},
    "adrinolinks.in": {"type": "adwall_js", "tier": 3},
    "mdiskshortner.link": {"type": "adwall_js", "tier": 3},
    "pdiskshortener.com": {"type": "adwall_js", "tier": 3},
    "linkpays.in": {"type": "adwall_js", "tier": 3},
    "linkpays.net": {"type": "adwall_js", "tier": 3},
    "shortzzy.in": {"type": "adwall_js", "tier": 3},
    "shortzzy.com": {"type": "adwall_js", "tier": 3},
    "shortzzy.link": {"type": "adwall_js", "tier": 3},
    "short2url.in": {"type": "adwall_js", "tier": 3},
    "shortex.in": {"type": "adwall_js", "tier": 3},
    "shortfaster.net": {"type": "adwall_js", "tier": 3},
    "earnl.in": {"type": "adwall_js", "tier": 3},
    "earningtime.in": {"type": "adwall_js", "tier": 3},
    "cashurl.win": {"type": "adwall_js", "tier": 3},
    "cutpaid.com": {"type": "adwall_js", "tier": 3},
    "cutwin.com": {"type": "adwall_js", "tier": 3},
    "cutearn.ca": {"type": "adwall_js", "tier": 3},
    "cuts-urls.com": {"type": "adwall_js", "tier": 3},
    "cut-win.com": {"type": "adwall_js", "tier": 3},
    "cut-urls.com": {"type": "adwall_js", "tier": 3},
    "linkpoi.in": {"type": "adwall_js", "tier": 3},
    "linkpoi.cc": {"type": "adwall_js", "tier": 3},
    "linkpoi.me": {"type": "adwall_js", "tier": 3},
    "linkduit.net": {"type": "adwall_js", "tier": 3},
    "link4earn.com": {"type": "adwall_js", "tier": 3},
    "loot-link.com": {"type": "adwall_js", "tier": 3},
    "lootlinks.co": {"type": "adwall_js", "tier": 3},
    "lootdest.com": {"type": "adwall_js", "tier": 3},
    "up4cash.com": {"type": "adwall_js", "tier": 3},
    "tmearn.com": {"type": "adwall_js", "tier": 3},
    "tmearn.net": {"type": "adwall_js", "tier": 3},
    "skip-url.me": {"type": "adwall_js", "tier": 3},
    "skiplink.io": {"type": "adwall_js", "tier": 3},
    "shortearn.eu": {"type": "adwall_js", "tier": 3},
    "shrinkearn.com": {"type": "adwall_js", "tier": 3},
    "shrinkforearn.in": {"type": "adwall_js", "tier": 3},
    "shrinkpay.in": {"type": "adwall_js", "tier": 3},
    "oylinkz.com": {"type": "adwall_js", "tier": 3},

    # ═══════════════════════════════════════════════════════════════
    # Tier 4: Social unlock
    # ═══════════════════════════════════════════════════════════════
    "sub2unlock.com": {"type": "social", "tier": 4},
    "sub2unlock.net": {"type": "social", "tier": 4},
    "sub4unlock.com": {"type": "social", "tier": 4},
    "rekonise.com": {"type": "social", "tier": 4},
    "mboost.me": {"type": "social", "tier": 4},
    "social-unlock.com": {"type": "social", "tier": 4},
    "ytsubme.com": {"type": "social", "tier": 4},
    "boost.ink": {"type": "social", "tier": 4},
    "work.ink": {"type": "social", "tier": 4},
    "unlocknow.net": {"type": "social", "tier": 4},
    "letsboost.net": {"type": "social", "tier": 4},
    "link2unlock.com": {"type": "social", "tier": 4},
    "complete2unlock.com": {"type": "social", "tier": 4},
    "do2unlock.com": {"type": "social", "tier": 4},
    "sub2get.com": {"type": "social", "tier": 4},
    "sub1s.com": {"type": "social", "tier": 4},
    "boostme.gg": {"type": "social", "tier": 4},
    "bst.gg": {"type": "social", "tier": 4},
    "bst.wtf": {"type": "social", "tier": 4},

    # ═══════════════════════════════════════════════════════════════
    # Tier 5: Drive sharers
    # ═══════════════════════════════════════════════════════════════
    "gdtot.com": {"type": "drive", "tier": 5},
    "gdtot.cfd": {"type": "drive", "tier": 5},
    "gdtot.nl": {"type": "drive", "tier": 5},
    "gdtot.pro": {"type": "drive", "tier": 5},
    "sharer.pw": {"type": "drive", "tier": 5},
    "hubdrive.net": {"type": "drive", "tier": 5},
    "hubdrive.tips": {"type": "drive", "tier": 5},
    "hubdrive.me": {"type": "drive", "tier": 5},
    "hubcloud.in": {"type": "drive", "tier": 5},
    "hubcloud.lol": {"type": "drive", "tier": 5},
    "hubcloud.dad": {"type": "drive", "tier": 5},
    "hubcloud.club": {"type": "drive", "tier": 5},
    "hubcloud.biz": {"type": "drive", "tier": 5},
    "hubcloud.art": {"type": "drive", "tier": 5},
    "katdrive.net": {"type": "drive", "tier": 5},
    "drivefire.net": {"type": "drive", "tier": 5},
    "kolop.net": {"type": "drive", "tier": 5},
    "appdrive.in": {"type": "drive", "tier": 5},
    "appdrive.info": {"type": "drive", "tier": 5},
    "megaup.net": {"type": "drive", "tier": 5},
    "uploadhaven.com": {"type": "drive", "tier": 5},
    "filepress.click": {"type": "drive", "tier": 5},
    "filepress.store": {"type": "drive", "tier": 5},
    "filepress.top": {"type": "drive", "tier": 5},
    "usersdrive.com": {"type": "drive", "tier": 5},
    "drivehub.link": {"type": "drive", "tier": 5},
    "drivelinks.me": {"type": "drive", "tier": 5},
    "gdflix.dad": {"type": "drive", "tier": 5},
    "gcloud.live": {"type": "drive", "tier": 5},

    # ═══════════════════════════════════════════════════════════════
    # Tier 6: Indian PPC shorteners (AdLinkFly / community-reported)
    # ═══════════════════════════════════════════════════════════════
    "babylinks.in": {"type": "adwall", "tier": 2},
    "anlinks.in": {"type": "adwall", "tier": 2},
    "bindaaslinks.com": {"type": "adwall", "tier": 2},
    "gtlinks.me": {"type": "adwall", "tier": 2},
    "gyanilinks.com": {"type": "adwall", "tier": 2},
    "indianshortner.in": {"type": "adwall", "tier": 2},
    "kpslink.in": {"type": "adwall", "tier": 2},
    "krownlinks.me": {"type": "adwall", "tier": 2},
    "linkshortx.in": {"type": "adwall", "tier": 2},
    "urlspay.in": {"type": "adwall", "tier": 2},
    "ziplinker.net": {"type": "adwall", "tier": 2},
    "du-link.in": {"type": "adwall", "tier": 2},
    "evolinks.in": {"type": "adwall", "tier": 2},
    "tinyfy.in": {"type": "adwall", "tier": 2},
    "earn2me.com": {"type": "adwall", "tier": 2},
    "earn2short.in": {"type": "adwall", "tier": 2},
    "appurl.io": {"type": "adwall", "tier": 2},
    "dalink.in": {"type": "adwall", "tier": 2},
    "dalinks.in": {"type": "adwall", "tier": 2},
    "dtglinks.in": {"type": "adwall", "tier": 2},
    "tglink.in": {"type": "adwall", "tier": 2},
    "instantearn.in": {"type": "adwall", "tier": 2},
    "viplinks.io": {"type": "adwall", "tier": 2},
    "monero-coin.win": {"type": "adwall", "tier": 2},
    "aiget.link": {"type": "adwall", "tier": 2},
    "vipurl.in": {"type": "adwall", "tier": 2},
    "royalearn.in": {"type": "adwall", "tier": 2},
    "vplink.in": {"type": "adwall", "tier": 2},
    "runurl.in": {"type": "adwall", "tier": 2},
    "flashlink.in": {"type": "adwall", "tier": 2},
    "lompat.in": {"type": "adwall", "tier": 2},
    "highdefdisc.com": {"type": "adwall", "tier": 2},
    "bidoox.com": {"type": "adwall", "tier": 2},
    "movieearn.com": {"type": "adwall", "tier": 2},
    "adshort.pro": {"type": "adwall", "tier": 2},
    "adshort.click": {"type": "adwall", "tier": 2},
    "linkvertise.in": {"type": "adwall", "tier": 2},
    "inshorts.link": {"type": "adwall", "tier": 2},
    "inshortner.com": {"type": "adwall", "tier": 2},
    "kingshort.in": {"type": "adwall", "tier": 2},
    "kiddyshort.com": {"type": "adwall", "tier": 2},
    "lootlink.cc": {"type": "adwall", "tier": 2},
    "clk.press": {"type": "adwall", "tier": 2},
    "cll.press": {"type": "adwall", "tier": 2},
}
